package br.com.clinicmanager.enums;

public enum Specialty {
    CARDIOLOGY, DERMATOLOGY, NEUROLOGY, PEDIATRICS, PSYCHOLOGY, PHYSIOTHERAPY, DENTISTRY, ORTHOPEDICS, PSYCHIATRY, GYNECOLOGY, ONCOLOGY, NUTRITION
}
